from scripts.common import parse_names_and_sequences

configfile: os.path.join(workflow.basedir, "..", "config", "config.yaml")

# path to metadata
METADATA = config["genome_info"]

# directory to sequences
SEQDIR = config["sequence_dir"]

# directory to save the results
RESULTS_DIR = config["results_dir"]

# get genome names and sequences path
GENOME, SEQUENCE_MAP = parse_names_and_sequences(METADATA, SEQDIR)

# rules
include: "rules/setup.smk"
include: "rules/prediction.smk"
include: "rules/evaluation.smk"

# master target rule
rule all:
    input: 
        expand(os.path.join(RESULTS_DIR, "results", "{genome}_all_coordinates.txt"), genome=GENOME),
        expand(os.path.join(RESULTS_DIR, "results", "{genome}_final_coordinates.txt"), genome=GENOME),
        expand(os.path.join(RESULTS_DIR, "results", "{genome}_whole_genome_coordinates.txt"), genome=GENOME),
        expand(os.path.join(RESULTS_DIR, "results", "checkv_evaluation", "{genome}", "quality_summary.tsv"), genome=GENOME)

