resources:
    big_mem: 128000      
    big_cpu: 16         

    med_mem: 64000      
    med_cpu: 8         

    small_mem: 16000      
    small_cpu: 4  

    tiny_mem: 6000

genomad:
  sensitivity: 7.5

cenote_taker3:
  settings: "-p T --wrap F --lin_minimum_hallmark_genes 2"
